version: "3.1"
services:
  database:
    container_name: spring-register
    image: mysql:latest
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      MYSQL_DATABASE: userDB
    network_mode: bridge
    env_file:
      - .env